name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set environment variables
      run: export LATEST_BASE_COMMIT=git rev-parse ${{ github.sha }}^@ | grep -Fvx ${{ github.event.pull_request.head.sha }}
    - name: Build docker Image
      run: echo $LATEST_BASE_COMMIT
      # run: docker build . --file Dockerfile --tag my-image-name:pr-${{ github.event.number }}_${{ env.LATEST_BASE_COMMIT }}
