name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [labeled, unlabeled]
jobs:

  build:

    runs-on: ubuntu-latest
    if: ${{ github.event.number != null && contains(github.event.pull_request.labels.*.name, 'build test environment') }}

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{ github.ref.id }}
