name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        SHA=${{ github.event.pull_request.head.sha }} | cut -c1-10 
        docker build . --file Dockerfile --tag my-image-name:pr-${{ github.event.number }}_${{ SHA }}
