name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set environment variables
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Build docker Image
      run: docker build . --file Dockerfile --tag my-image-name:pr-${{ github.event.number }}_$(echo $GITHUB_SHA | cut -c 1-6)
