name: Step 2

on:
  workflow_run:
    workflows:
      - experiment
    types:
      - completed

jobs:
  job3:
    runs-on: ubuntu-latest
    name: Final countdown

    steps:
      - name: Final countdown step
        run: echo "All dependencies satisfied"